# Generated by Django 5.0.6 on 2024-07-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('days', models.IntegerField(default=30)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('freezable', models.BooleanField(default=False)),
                ('freeze_no', models.IntegerField(default=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LockerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('days', models.IntegerField(default=30)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('freezable', models.BooleanField(default=False)),
                ('freeze_no', models.IntegerField(default=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('days', models.IntegerField(default=30)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('freezable', models.BooleanField(default=False)),
                ('freeze_no', models.IntegerField(default=7)),
                ('invitations', models.IntegerField(default=0)),
                ('for_students', models.BooleanField(default=False)),
                ('validity', models.IntegerField(default=30)),
                ('is_duration', models.BooleanField(default=True)),
                ('classes_no', models.IntegerField(blank=True, default=8, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
