# Generated by Django 5.0.6 on 2024-09-23 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('days', models.IntegerField(blank=True, default=30, null=True)),
                ('subscription_type', models.CharField(choices=[('main', 'اشتراك أساسى'), ('sub', 'اشتراك إضافى'), ('locker', 'اشتراك لوكر')], max_length=12)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('freezable', models.BooleanField(default=False)),
                ('freeze_no', models.IntegerField(blank=True, default=7, null=True)),
                ('invitations', models.IntegerField(default=0)),
                ('for_students', models.BooleanField(default=False)),
                ('validity', models.IntegerField(default=30, null=True)),
                ('is_duration', models.BooleanField(default=True)),
                ('classes_no', models.IntegerField(blank=True, default=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('freeze_days_used', models.PositiveIntegerField(default=0)),
                ('freeze_start_date', models.DateField(blank=True, null=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('unfreeze_date', models.DateField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, default=0, null=True)),
                ('attendance_days', models.IntegerField(blank=True, default=0, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='clients.client')),
            ],
        ),
    ]
