# Generated by Django 5.0.6 on 2024-07-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='client',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
    ]
