# Generated by Django 5.0.6 on 2024-09-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='invitations_used',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
