# Generated by Django 5.0.6 on 2024-07-28 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_delete_subscription'),
        ('subscriptions', '0003_remove_subscription_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='clients.client'),
            preserve_default=False,
        ),
    ]
