# Generated by Django 5.0.6 on 2024-09-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_invitations_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
