# Generated by Django 5.0.6 on 2024-07-28 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_end_date_subscription_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalPlan',
        ),
        migrations.DeleteModel(
            name='LockerPlan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='object_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.subscriptionplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription_type',
            field=models.CharField(choices=[('main', 'Main Plan'), ('sub', 'Sub Plan'), ('locker', 'Locker Plan')], default='main', max_length=12),
            preserve_default=False,
        ),
    ]
