# Generated by Django 5.0.6 on 2024-10-01 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_initial'),
        ('subscriptions', '0006_alter_invitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financials.transaction'),
        ),
    ]
