# Generated by Django 5.0.6 on 2024-07-28 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_delete_additionalplan_delete_lockerplan_and_more'),
        ('users', '0016_remove_employee_subscription_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscription_type',
            field=models.CharField(choices=[('main', 'اشتراك أساسى'), ('sub', 'اشتراك إضافى'), ('locker', 'اشتراك لوكر')], max_length=12),
        ),
    ]
