# Generated by Django 5.0.6 on 2024-07-29 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_subscription_trainer_and_more'),
        ('users', '0016_remove_employee_subscription_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_subscriptions', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training', to='users.employee'),
        ),
    ]
