# Generated by Django 5.0.6 on 2024-10-01 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_initial'),
        ('subscriptions', '0007_subscription_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financials.transaction'),
        ),
    ]
