# Generated by Django 5.0.6 on 2024-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscription_referrer_alter_subscription_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='total_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
