# Generated by Django 5.0.6 on 2024-09-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscription_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='freeze_no',
            field=models.IntegerField(default=7, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='validity',
            field=models.IntegerField(default=30, null=True),
        ),
    ]
