# Generated by Django 5.0.6 on 2024-10-31 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscription_created_at_subscription_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='created_by',
            new_name='added_by',
        ),
    ]
