# Generated by Django 5.0.6 on 2024-09-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_alter_subscriptionplan_freeze_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='days',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
