# Generated by Django 5.0.6 on 2025-03-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_rename_created_by_subscription_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
