# Generated by Django 5.0.6 on 2024-09-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_alter_subscriptionplan_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='attendance_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
