# Generated by Django 5.0.6 on 2024-09-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_subscription_attendance_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='freeze_no',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
    ]
