# Generated by Django 5.0.6 on 2024-07-18 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_subscription_client_alter_subscription_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 18, 18, 22, 3, 814942, tzinfo=datetime.timezone.utc)),
        ),
    ]
