# Generated by Django 5.0.6 on 2024-09-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
