# Generated by Django 5.0.6 on 2024-09-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_attendance_guest_alter_attendance_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
