# Generated by Django 5.0.6 on 2024-07-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bar_code',
            field=models.ImageField(blank=True, null=True, upload_to='bar_codes'),
        ),
        migrations.AddField(
            model_name='client',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
