# Generated by Django 5.0.6 on 2024-11-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
