# Generated by Django 5.0.6 on 2024-07-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_bar_code_client_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='bar_code',
            new_name='barcode',
        ),
    ]
