# Generated by Django 5.0.6 on 2024-07-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_rename_bar_code_client_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes'),
        ),
    ]
