# Generated by Django 5.0.6 on 2024-11-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_height_client_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
