# Generated by Django 5.0.6 on 2024-07-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='current_subscription',
        ),
        migrations.RemoveField(
            model_name='client',
            name='subscription_history',
        ),
    ]
