# Generated by Django 5.0.6 on 2024-11-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='requested_photo',
            field=models.ImageField(blank=True, null=True, upload_to='requested/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
