# Generated by Django 5.0.6 on 2024-07-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_remove_client_current_subscription_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
