# Generated by Django 5.0.6 on 2024-12-05 04:29

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=clients.models.client_photo_upload_path),
        ),
    ]
