# Generated by Django 5.0.6 on 2024-07-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_delete_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='trainer',
        ),
    ]
