# Generated by Django 5.0.6 on 2024-12-05 22:50

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_client_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='created_at',
            field=models.DateField(default=clients.models.get_today),
        ),
    ]
