# Generated by Django 5.0.6 on 2024-12-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_new_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
