# Generated by Django 5.0.6 on 2025-04-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_new_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='unique_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
