# Generated by Django 5.0.6 on 2024-09-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='national_id',
        ),
    ]
