# Generated by Django 5.0.6 on 2024-09-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_remove_client_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
