# Generated by Django 5.0.6 on 2024-07-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tpye', models.CharField(choices=[('expenses', 'Expenses'), ('incomes', 'Incomes')], max_length=100)),
            ],
        ),
    ]
