# Generated by Django 5.0.6 on 2024-09-23 04:05

import django.core.validators
import financials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=financials.models.current_date)),
                ('total_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fully_paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['fully_paid'],
            },
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=financials.models.current_date)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('financial_type', models.CharField(choices=[('expenses', 'Expenses'), ('incomes', 'Incomes')], max_length=10)),
                ('system_related', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('private_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subscription_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vacations', models.IntegerField(default=0)),
                ('working_hours', models.IntegerField(default=8)),
                ('working_days', models.IntegerField(default=26)),
            ],
            options={
                'verbose_name_plural': 'Salaries',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
