# Generated by Django 5.0.6 on 2024-07-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialitem',
            old_name='tpye',
            new_name='financial_type',
        ),
    ]
