# Generated by Django 5.0.6 on 2024-09-23 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financials', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='users.employee'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='advance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financials.advance'),
        ),
        migrations.AddField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.financialitem'),
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('employee', 'month', 'year')},
        ),
    ]
