# Generated by Django 5.0.6 on 2024-07-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_rename_tpye_financialitem_financial_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialitem',
            name='financial_type',
            field=models.CharField(choices=[('expenses', 'Expenses'), ('incomes', 'Incomes')], max_length=10),
        ),
    ]
