# Generated by Django 5.0.6 on 2024-07-23 02:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_remove_income_category_transaction_delete_expense_and_more'),
        ('users', '0015_remove_user_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('private_percent', models.IntegerField(default=0)),
                ('subscription_percent', models.IntegerField(default=0)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('got_advance', models.BooleanField(default=False)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vacations', models.IntegerField(default=0)),
                ('working_hours', models.IntegerField(default=8)),
                ('working_days', models.IntegerField(default=26)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
