# Generated by Django 5.0.6 on 2024-07-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0006_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name_plural': 'Salaries'},
        ),
    ]
