# Generated by Django 5.0.6 on 2024-07-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_alter_salary_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
    ]
