# Generated by Django 5.0.6 on 2024-07-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_alter_salary_base_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='private_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='salary',
            name='subscription_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
