# Generated by Django 5.0.6 on 2024-07-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0009_alter_salary_private_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='advance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
