# Generated by Django 5.0.6 on 2024-07-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0010_salary_advance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='private_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='subscription_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
