# Generated by Django 5.0.6 on 2024-08-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0011_alter_salary_private_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialitem',
            name='system_related',
            field=models.BooleanField(default=False),
        ),
    ]
