# Generated by Django 5.0.6 on 2024-09-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0012_financialitem_system_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='advance_date',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='advance_payment',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='got_advance',
        ),
    ]
