# Generated by Django 5.0.6 on 2024-09-09 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0013_remove_salary_advance_date_and_more'),
        ('users', '0023_alter_employee_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_taken', models.DateField(auto_now_add=True)),
                ('total_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fully_paid', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='users.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financials.advance')),
            ],
        ),
    ]
