# Generated by Django 5.0.6 on 2024-09-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0014_advance_advancepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advance',
            old_name='date_taken',
            new_name='date',
        ),
    ]
