# Generated by Django 5.0.6 on 2024-09-09 19:08

import financials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0015_rename_date_taken_advance_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advance',
            options={'ordering': ['fully_paid']},
        ),
        migrations.AlterField(
            model_name='advance',
            name='date',
            field=models.DateField(default=financials.models.current_date),
        ),
    ]
