# Generated by Django 5.0.6 on 2024-09-10 09:08

import financials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0016_alter_advance_options_alter_advance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='payment_date',
            field=models.DateField(default=financials.models.current_date),
        ),
    ]
