# Generated by Django 5.0.6 on 2024-09-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0017_alter_advancepayment_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancepayment',
            old_name='payment_date',
            new_name='date',
        ),
    ]
