# Generated by Django 5.0.6 on 2024-08-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='gym_data/'),
        ),
        migrations.AlterField(
            model_name='gymdata',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gymdata',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='gym_data/'),
        ),
        migrations.AlterField(
            model_name='gymdata',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gymdata',
            name='title',
            field=models.CharField(default='GYM', max_length=255),
        ),
    ]
