# Generated by Django 5.0.6 on 2024-08-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_data', '0003_alter_gymdata_logo_alter_link_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymdata',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='gym_data/'),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='gym_data/'),
        ),
    ]
