# Generated by Django 5.0.6 on 2024-08-30 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_data', '0004_alter_gymdata_logo_alter_link_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='name',
            new_name='title',
        ),
    ]
