import {
    FaUsers,
    FaCog,
    FaUserPlus,
    FaUserSlash,
    FaSearch,
    FaFilter,
    FaBarcode,
    FaMoneyBill,
    FaFileAlt,
    FaRegFileAlt,
    FaBirthdayCake,
    FaUserTie,
} from "react-icons/fa";
import {
    MdSupervisorAccount,
    MdPerson,
    MdSecurity,
    MdSubscriptions,
    MdLock,
    MdMoneyOff,
    MdAssignment,
    MdReport,
    MdAddCircle,
} from "react-icons/md";
import { FaShop } from "react-icons/fa6";
import { RiShoppingBag3Fill } from "react-icons/ri";
import { IoBagCheck } from "react-icons/io5";
import Managers from "../components/users/Managers";
import Employees from "../components/users/Employees";
import Moderators from "../components/users/Moderators";
import Permissions from "../components/users/Permissions";
import Subscriptions from "../components/settings/Subscriptions";
import Lockers from "../components/settings/Lockers";
import AdditionalPlans from "../components/settings/AdditionalPlans";
import FinancialItems from "../components/settings/FinancialItems";
import EmployeeSettings from "../components/settings/EmployeeSettings";

export const routes = [
    {
        id: 1,
        title: "إدارة المستخدمين",
        name: "user-management",
        url: "/users",
        icon: <FaUsers />,
        children: [
            {
                id: 1,
                title: "المديرين",
                name: "managers",
                url: "/users/managers",
                icon: <FaUserTie />,
                element: <Managers />,
                permissions: "unadjustable",
            },
            {
                id: 2,
                title: "الموظفين",
                name: "staff",
                url: "/users/staff",
                icon: <MdPerson />,
                element: <Employees />,
            },
            {
                id: 3,
                title: "المشرفين",
                name: "moderators",
                url: "/users/moderators",
                icon: <MdSupervisorAccount />,
                element: <Moderators />,
            },
            {
                id: 4,
                title: "الصلاحيات",
                name: "permissions",
                url: "/users/permissions",
                icon: <MdSecurity />,
                element: <Permissions />,
                permissions: [
                    { id: 1, value: "تعديل الصلاحيات", name: "permissions" },
                ],
            },
        ],
    },
    {
        id: 2,
        title: "إعدادات النظام",
        name: "system-settings",
        url: "/settings",
        icon: <FaCog />,
        children: [
            {
                id: 1,
                title: "الاشتراكات",
                name: "plans",
                url: "/settings/plans",
                icon: <MdSubscriptions />,
                element: <Subscriptions />,
            },
            {
                id: 2,
                title: "اللوكر",
                name: "lockers",
                url: "/settings/lockers",
                icon: <MdLock />,
                element: <Lockers />,
            },
            // {
            //     id: 3,
            //     title: "أرقام اللوكر",
            //     url: "/settings/lockers-numbers",
            //     icon: <MdLockOpen />,
            // },
            {
                id: 3,
                title: "الاشتراكات الإضافية",
                name: "additional-plans",
                url: "/settings/additional-plans",
                icon: <MdAddCircle />,
                element: <AdditionalPlans />,
            },
            {
                id: 4,
                title: "بنود المصروفات",
                name: "expenses-items",
                url: "/settings/expenses",
                icon: <FaMoneyBill />,
                element: <FinancialItems />,
            },
            {
                id: 5,
                title: "الموظفين",
                name: "staff-settings",
                url: "/settings/staff",
                icon: <MdPerson />,
                element: <EmployeeSettings />,
            },
        ],
    },
    {
        id: 3,
        title: "الأعضاء",
        name: "clients",
        url: "/clients",
        icon: <FaUsers />,
        children: [
            {
                id: 1,
                title: "إضافة عضو",
                name: "add-client",
                url: "/clients/add",
                icon: <FaUserPlus />,
            },
            {
                id: 2,
                title: "حظر عضو",
                name: "block-client",
                url: "/clients/block",
                icon: <FaUserSlash />,
                permissions: "unadjustable",
            },
            {
                id: 3,
                title: "بحث فردى",
                name: "individual-search",
                url: "/clients/search",
                icon: <FaSearch />,
                permissions: "unadjustable",
            },
            {
                id: 4,
                title: "بحث مجموعة",
                name: "group-search",
                url: "/clients/filter",
                icon: <FaFilter />,
                permissions: "unadjustable",
            },
        ],
    },
    {
        id: 4,
        title: "الاشتراكات",
        name: "subscriptions",
        url: "/subscriptions",
        icon: <MdSubscriptions />,
        children: [
            {
                id: 1,
                title: "إضافة اشتراك",
                name: "add-subscription",
                url: "/subscriptions/add",
                icon: <MdSubscriptions />,
            },
            {
                id: 2,
                title: "الاشتراكات خلال فترة",
                name: "subscriptions-within-duration",
                url: "/subscriptions/within-duration",
                icon: <MdSubscriptions />,
                permissions: "unadjustable",
            },
            {
                id: 3,
                title: "الاشتراكات الحالية",
                name: "current-subscriptions",
                url: "/subscriptions/current-active",
                icon: <MdSubscriptions />,
                permissions: "unadjustable",
            },
            {
                id: 4,
                title: "بحث",
                name: "search-subscriptions",
                url: "/subscriptions/search",
                icon: <FaSearch />,
                permissions: "unadjustable",
            },
            {
                id: 5,
                title: "إيقاف الاشتراكات",
                name: "freeze-subscriptions",
                url: "/subscriptions/freeze",
                icon: <MdMoneyOff />,
                permissions: "unadjustable",
            },
            {
                id: 6,
                title: "الاشتراكات المنتهية",
                name: "expired-subscriptions",
                url: "/subscriptions/expired",
                icon: <MdSubscriptions />,
                permissions: "unadjustable",
            },
        ],
    },
    {
        id: 5,
        title: "الباركود",
        name: "barcode",
        url: "/barcode",
        icon: <FaBarcode />,
        permissions: "unadjustable",
        children: [
            {
                id: 1,
                title: "الباركود اليومي",
                name: "today-barcode",
                url: "/barcode/today",
                icon: <FaBarcode />,
            },
            {
                id: 2,
                title: "سجل الباركود",
                name: "barcode-attendance",
                url: "/barcode/attendance",
                icon: <FaBarcode />,
            },
        ],
    },
    {
        id: 6,
        title: "المتجر",
        name: "store",
        url: "/store",
        icon: <FaShop />,
        children: [
            {
                id: 1,
                title: "المنتجات",
                name: "products",
                url: "/store/products",
                icon: <RiShoppingBag3Fill />,
            },
            {
                id: 2,
                title: "عمليات الشراء",
                name: "sales",
                url: "/store/sales",
                icon: <IoBagCheck />,
                permissions: "unadjustable",
            },
        ],
    },
    {
        id: 7,
        title: "الشئون المالية",
        name: "financials",
        url: "/financials",
        icon: <FaMoneyBill />,
        children: [
            {
                id: 1,
                title: "الإيرادات",
                name: "incomes",
                url: "/financials/incomes",
                icon: <FaMoneyBill />,
            },
            {
                id: 2,
                title: "المصروفات",
                name: "expenses",
                url: "/financials/expenses",
                icon: <FaMoneyBill />,
            },
        ],
    },
    {
        id: 8,
        title: "التقارير",
        name: "reports",
        url: "/reports",
        icon: <FaFileAlt />,
        permissions: [{ id: 1, value: "عرض التقارير", name: "reports" }],
        children: [
            {
                id: 1,
                title: "التقارير اليومية",
                name: "daily-reports",
                url: "/reports/daily",
                icon: <FaRegFileAlt />,
            },
            {
                id: 2,
                title: "التقارير الشهرية",
                name: "monthly-reports",
                url: "/reports/monthly",
                icon: <FaRegFileAlt />,
            },
            {
                id: 3,
                title: "التقارير خلال فترة",
                name: "within-duration-reports",
                url: "/reports/within-duration",
                icon: <MdReport />,
            },
            {
                id: 4,
                title: "تقارير الاشتراكات",
                name: "subscription-reports",
                url: "/reports/subscriptions",
                icon: <MdAssignment />,
            },
            {
                id: 5,
                title: "تقارير أعياد الميلاد",
                name: "birthday-reports",
                url: "/reports/birthdays",
                icon: <FaBirthdayCake />,
            },
        ],
    },
];

const formMapping = {};
