# Generated by Django 5.0.6 on 2024-08-27 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_attendance'),
        ('shop', '0004_rename_price_product_sell_price_product_cost_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='sale',
            name='after_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
