# Generated by Django 5.0.6 on 2024-08-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_saleitem_product_alter_saleitem_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
