# Generated by Django 5.0.6 on 2024-08-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_sale_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='state',
            field=models.CharField(choices=[('pending', 'معلق'), ('sold', 'تم البيع')], default='pending', max_length=10),
        ),
    ]
