# Generated by Django 5.0.6 on 2024-08-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_sale_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='confirmed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
