# Generated by Django 5.0.6 on 2024-08-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='subscription',
            new_name='plan',
        ),
    ]
