# Generated by Django 5.0.6 on 2024-08-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('product', 'عرض على منتج'), ('plan', 'عرض على اشتراك')], max_length=12),
        ),
    ]
