# Generated by Django 5.0.6 on 2024-07-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employeecity_employeenationality_employeetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='subscription_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
