# Generated by Django 5.0.6 on 2024-07-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_employee_birth_date_alter_user_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeCity',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='EmployeeNationality',
            new_name='Nationality',
        ),
    ]
