# Generated by Django 5.0.6 on 2024-07-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_employee_age_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='subscription_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
