# Generated by Django 5.0.6 on 2024-07-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_employee_subscription_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='add_by',
            new_name='added_by',
        ),
    ]
