# Generated by Django 5.0.6 on 2024-07-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_employee_added_by_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='gender',
            new_name='gander',
        ),
    ]
