# Generated by Django 5.0.6 on 2024-07-15 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_gender_employee_gander'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee', unique=True),
        ),
    ]
