# Generated by Django 5.0.6 on 2024-07-15 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_moderator_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee'),
        ),
    ]
