# Generated by Django 5.0.6 on 2024-07-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_moderator_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
