# Generated by Django 5.0.6 on 2024-07-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_number',
        ),
    ]
