# Generated by Django 5.0.6 on 2024-07-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_user_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='subscription_percent',
        ),
    ]
