# Generated by Django 5.0.6 on 2024-08-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_employee_subscription_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('add_manager', 'Can add manager'), ('change_manager', 'Can change manager'), ('delete_manager', 'Can delete manager'), ('view_manager', 'Can view manager'), ('add_moderator', 'Can add moderator'), ('change_moderator', 'Can change moderator'), ('delete_moderator', 'Can delete moderator'), ('view_moderator', 'Can view moderator')]},
        ),
    ]
