# Generated by Django 5.0.6 on 2024-08-15 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_is_root'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('add_manager', 'Can add manager'), ('change_manager', 'Can change manager'), ('delete_manager', 'Can delete manager'), ('view_manager', 'Can view manager')]},
        ),
    ]
