# Generated by Django 5.0.6 on 2024-08-16 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('add_employeesettings', 'Can add employee settings'), ('change_employeesettings', 'Can change employee settings'), ('delete_employeesettings', 'Can delete employee settings'), ('view_employeesettings', 'Can view employee settings')]},
        ),
    ]
