# Generated by Django 5.0.6 on 2024-08-16 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
