# Generated by Django 5.0.6 on 2024-08-16 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'permissions': [('add_employeesettings', 'Can add employee settings'), ('change_employeesettings', 'Can change employee settings'), ('delete_employeesettings', 'Can delete employee settings'), ('view_employeesettings', 'Can view employee settings')]},
        ),
        migrations.AlterModelOptions(
            name='citydistrict',
            options={'permissions': [('add_employeesettings', 'Can add employee settings'), ('change_employeesettings', 'Can change employee settings'), ('delete_employeesettings', 'Can delete employee settings'), ('view_employeesettings', 'Can view employee settings')]},
        ),
        migrations.AlterModelOptions(
            name='employeetype',
            options={'permissions': [('add_employeesettings', 'Can add employee settings'), ('change_employeesettings', 'Can change employee settings'), ('delete_employeesettings', 'Can delete employee settings'), ('view_employeesettings', 'Can view employee settings')]},
        ),
        migrations.AlterModelOptions(
            name='maritalstatus',
            options={'permissions': [('add_employeesettings', 'Can add employee settings'), ('change_employeesettings', 'Can change employee settings'), ('delete_employeesettings', 'Can delete employee settings'), ('view_employeesettings', 'Can view employee settings')]},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'permissions': [('add_employeesettings', 'Can add employee settings'), ('change_employeesettings', 'Can change employee settings'), ('delete_employeesettings', 'Can delete employee settings'), ('view_employeesettings', 'Can view employee settings')]},
        ),
    ]
