# Generated by Django 5.0.6 on 2024-08-25 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_city_options_alter_citydistrict_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
